namespace LOOP.Models
{
    public class User
    {
        public int Id { get; set; }

        public string Name { get; set; } = string.Empty;

        public string Email { get; set; } = string.Empty;

        public string PasswordHash { get; set; } = string.Empty;

        public string Role { get; set; } = "VIEWER";

        // Foreign Key
        public int WorkspaceId { get; set; }

        public Workspace Workspace { get; set; } = null!;

        // Reports generated by this user
        public ICollection<Report> Reports { get; set; } = new List<Report>();
    }
}